from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass

from ollama import chat
from pydantic import BaseModel


# Stores the execution result and metadata from an LLM call
@dataclass
class LLMResult:
    content: str        # The response text generated by the model
    done_reason: str    # Reason for completion (e.g., "stop", "length")
    prompt_tokens: int
    output_tokens: int


"""
Executes a chat completion request using a local Ollama model.

Returns:
    LLMResult: Object containing generated text content and call metadata.
"""
def llm_chat(
    backend: dict,      # Backend configuration mapping (reserved for multi-backend extensions)
    local_model: str,   # Name/tag of the local Ollama model to invoke
    system_prompt: str,
    user_prompt: str,
    temperature: float,
    *,
    schema_model: type[BaseModel] | None = None,
    json_mode: bool = False,
    seed: int | None = None,
    num_ctx: int | None = None,     # Context window size for the generation session
    max_tokens: int | None = None,
) -> LLMResult:

    # Configure generation options for Ollama
    options = {"temperature": temperature}
    if seed is not None:
        options["seed"] = seed
    if num_ctx:
        options["num_ctx"] = num_ctx
    if max_tokens:
        options["num_predict"] = max_tokens

    # Determine response format schema
    if schema_model is not None:
        fmt = schema_model.model_json_schema()
    else:
        fmt = "json" if json_mode else None

    # Invoke local Ollama chat backend
    r = chat(
        model=local_model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        options=options,
        format=fmt,
    )

    return LLMResult(
        content=r["message"]["content"],
        done_reason=r.get("done_reason") or "unknown",
        prompt_tokens=r.get("prompt_eval_count") or 0,
        output_tokens=r.get("eval_count") or 0,
    )

"""
Applies a function to each item in the iterable while preserving order.

Executes sequentially if max_workers <= 1 or if there is only 1 item;
otherwise uses thread concurrency via ThreadPoolExecutor. 

Returns:
    List[R]: List of results corresponding to the input items in original order.
"""
def run_parallel(
    fn,                     # Callable function to apply to each element
    items,                  # Collection of items to process
    max_workers: int = 1    # Maximum number of thread workers. Defaults to 1 (sequential)
) -> list:    

    items = list(items)

    # Fallback to sequential execution for single worker or single item
    if max_workers <= 1 or len(items) <= 1:
        return [fn(i) for i in items]

    # Execute in parallel maintaining item ordering
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        return list(ex.map(fn, items))